/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FeaturePage: typeof import('./src/components/FeaturePage.vue')['default']
    GalleryPage: typeof import('./src/components/GalleryPage.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    SliderPicture: typeof import('./src/components/SliderPicture.vue')['default']
    TitlePage: typeof import('./src/components/TitlePage.vue')['default']
  }
}
