/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClientPage: typeof import('./src/components/ClientPage.vue')['default']
    FeaturePage: typeof import('./src/components/FeaturePage.vue')['default']
    FlowPage: typeof import('./src/components/FlowPage.vue')['default']
    GalleryPage: typeof import('./src/components/GalleryPage.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    HeaderFull: typeof import('./src/components/HeaderFull.vue')['default']
    QApage: typeof import('./src/components/QApage.vue')['default']
    SliderPicture: typeof import('./src/components/SliderPicture.vue')['default']
    SpotPage: typeof import('./src/components/SpotPage.vue')['default']
    TitlePage: typeof import('./src/components/TitlePage.vue')['default']
  }
}
